using System.Globalization;
using System.Resources;
using System.Collections.Generic;

namespace PaperTodo;

public static class Strings
{
    private static readonly ResourceManager Manager = new("PaperTodo.Resources.Strings", typeof(Strings).Assembly);

    private static readonly IReadOnlyDictionary<string, string[]> Supplemental =
        new Dictionary<string, string[]>(StringComparer.Ordinal)
        {
            ["PlannerTitle"] = ["纸隅 · 计划台", "PaperNook · Planner", "PaperNook · プランナー", "PaperNook · 플래너"],
            ["PlannerMore"] = ["更多操作", "More actions", "その他の操作", "더 많은 작업"],
            ["PlannerTaskCount"] = ["{0} 项任务", "{0} tasks", "{0} 件のタスク", "작업 {0}개"],
            ["PlannerMoreDetails"] = ["标签与时长", "Tags and duration", "タグと所要時間", "태그 및 소요 시간"],
            ["PlannerArrangeTime"] = ["安排时间", "Schedule time", "時間を設定", "시간 예약"],
            ["PlannerCloseDetails"] = ["关闭详情", "Close details", "詳細を閉じる", "상세 닫기"],
            ["PlannerUnsaved"] = ["有未保存的更改", "Unsaved changes", "未保存の変更があります", "저장되지 않은 변경 사항"],
            ["PlannerUnsavedChoice"] = ["任务有未保存的修改。保存后继续，还是放弃修改？", "Save task changes before continuing, or discard them?", "続ける前に変更を保存しますか、それとも破棄しますか？", "계속하기 전에 작업 변경을 저장하거나 버릴까요?"],
            ["PlannerUnsavedQuickAdd"] = ["还有未添加的任务文字。保存会将它添加到当前目标位置。", "Task text has not been added. Save adds it to the current destination.", "まだ追加していないタスクがあります。保存すると現在の追加先に追加します。", "아직 추가하지 않은 작업이 있습니다. 저장하면 현재 대상에 추가합니다."],
            ["PlannerDiscardChanges"] = ["放弃修改", "Discard changes", "変更を破棄", "변경 버리기"],
            ["PlannerTaskName"] = ["任务名称", "Task name", "タスク名", "작업 이름"],
            ["PlannerShowAdded"] = ["查看刚添加的任务", "Show the added task", "追加したタスクを表示", "추가한 작업 보기"],
            ["PlannerQuickAddInbox"] = ["添加任务到收集箱…", "Add a task to Inbox…", "受信箱にタスクを追加…", "수집함에 작업 추가…"],
            ["NormalExitSaveFailure"] = ["退出已取消：最新修改尚未保存到磁盘。软件和修改仍保留；请检查磁盘空间及数据目录权限，恢复后重试退出。", "Exit cancelled: the latest changes could not be saved to disk. The app and changes remain open. Check disk space and data-folder permissions, then retry exiting.", "終了を中止しました。最新の変更を保存できませんでした。アプリと変更は保持されています。空き容量とデータフォルダーの権限を確認してから終了を再試行してください。", "종료 취소: 최신 변경을 디스크에 저장하지 못했습니다. 앱과 변경은 유지됩니다. 디스크 공간과 데이터 폴더 권한을 확인한 후 종료를 다시 시도하세요."],
            ["PlannerOpen"] = ["打开清单与日程", "Open lists and schedule", "リストと予定を開く", "목록 및 일정 열기"],
            ["PlannerInbox"] = ["收集箱", "Inbox", "受信箱", "수집함"],
            ["PlannerToday"] = ["今天", "Today", "今日", "오늘"],
            ["PlannerTomorrow"] = ["明天", "Tomorrow", "明日", "내일"],
            ["PlannerWeek"] = ["最近七天", "Next seven days", "今後7日間", "앞으로 7일"],
            ["PlannerAll"] = ["全部任务", "All tasks", "すべてのタスク", "모든 작업"],
            ["PlannerCompleted"] = ["已完成", "Completed", "完了", "완료됨"],
            ["PlannerAgenda"] = ["日程", "Schedule", "予定", "일정"],
            ["PlannerLists"] = ["我的清单", "My lists", "マイリスト", "내 목록"],
            ["PlannerUngrouped"] = ["未分组", "Ungrouped", "未分類", "그룹 없음"],
            ["PlannerUntitled"] = ["未命名清单", "Untitled list", "無題のリスト", "제목 없는 목록"],
            ["PlannerNewList"] = ["新建清单", "New list", "リストを作成", "새 목록"],
            ["PlannerEditList"] = ["编辑清单", "Edit list", "リストを編集", "목록 편집"],
            ["PlannerListName"] = ["清单名称", "List name", "リスト名", "목록 이름"],
            ["PlannerFolder"] = ["分组（例如工作、学习）", "Folder (e.g. work, study)", "グループ（仕事、学習など）", "그룹 (예: 업무, 학습)"],
            ["PlannerPin"] = ["钉到桌面", "Pin to desktop", "デスクトップに固定", "바탕 화면에 고정"],
            ["PlannerPinLimit"] = ["最多钉住 20 个视图，请先关闭一个。", "At most 20 pinned views; close one first.", "固定できるビューは最大20です。先に1つ閉じてください。", "고정 보기는 최대 20개입니다. 먼저 하나를 닫으세요."],
            ["PlannerSearch"] = ["搜索标题、标签、清单", "Search tasks, tags, lists", "タスク・タグ・リストを検索", "작업, 태그, 목록 검색"],
            ["PlannerQuickAdd"] = ["输入任务，按 Enter 添加", "Enter a task, press Enter to add", "タスクを入力し Enter で追加", "작업 입력 후 Enter로 추가"],
            ["PlannerAdd"] = ["添加", "Add", "追加", "추가"],
            ["PlannerAdded"] = ["已添加；日期视图中的新任务存放在收集箱。", "Added; tasks created in date views are stored in Inbox.", "追加しました。日付ビューの新規タスクは受信箱に保存されます。", "추가됨. 날짜 보기의 새 작업은 수집함에 저장됩니다."],
            ["PlannerEmpty"] = ["这里还没有任务。先记下一件事，或调整搜索条件。", "No tasks here. Add a task or change the search.", "タスクはありません。追加するか検索条件を変更してください。", "작업이 없습니다. 작업을 추가하거나 검색을 변경하세요."],
            ["PlannerOverdue"] = ["已逾期", "Overdue", "期限切れ", "기한 초과"],
            ["PlannerPriority0"] = ["无优先级", "No priority", "優先度なし", "우선순위 없음"],
            ["PlannerPriority1"] = ["低优先级", "Low priority", "低優先度", "낮은 우선순위"],
            ["PlannerPriority2"] = ["中优先级", "Medium priority", "中優先度", "중간 우선순위"],
            ["PlannerPriority3"] = ["高优先级", "High priority", "高優先度", "높은 우선순위"],
            ["PlannerPriority"] = ["优先级", "Priority", "優先度", "우선순위"],
            ["PlannerPlannedDate"] = ["计划日期", "Planned date", "実行予定日", "계획 날짜"],
            ["PlannerDueDate"] = ["截止日期", "Deadline date", "期限日", "마감 날짜"],
            ["PlannerDuration"] = ["预计用时（分钟）", "Estimate (minutes)", "所要時間（分）", "예상 시간 (분)"],
            ["PlannerDurationError"] = ["预计用时请输入 5–1440 分钟。", "Enter 5–1440 minutes.", "5〜1440分を入力してください。", "5–1440분을 입력하세요."],
            ["PlannerTags"] = ["标签（用空格分隔）", "Tags (space separated)", "タグ（スペース区切り）", "태그 (공백 구분)"],
            ["PlannerStart"] = ["日程开始", "Schedule start", "予定開始", "일정 시작"],
            ["PlannerEnd"] = ["日程结束", "Schedule end", "予定終了", "일정 종료"],
            ["PlannerTimeHint"] = ["选择日期，时间填 14:00；按本机时区保存。开始与结束同时填写或同时清空。", "Choose dates and enter times such as 14:00; saved in local timezone. Fill or clear both ends.", "日付を選び14:00のように入力します。ローカル時間帯で保存し、開始・終了を両方設定または消去します。", "날짜를 선택하고 14:00처럼 입력하세요. 현지 시간대로 저장하며 시작과 종료를 함께 설정하거나 지우세요."],
            ["PlannerAmbiguousTime"] = ["当前时区的这个时间不存在或有两个含义，请选择其他时间。", "This local time is invalid or ambiguous; choose another time.", "この現地時刻は存在しないか曖昧です。別の時刻を選んでください。", "현지 시간이 없거나 모호합니다. 다른 시간을 선택하세요."],
            ["PlannerAiHelp"] = ["用 AI 帮忙安排", "Plan with AI", "AIで予定を立てる", "AI로 일정 계획"],
            ["PlannerAiHelpDetail"] = ["当前版本通过 MCP 接入外部 AI，不内置模型。\n\n在设置 → 实验功能中启用 MCP 和“允许 AI 日程建议”，无需开启完整写入。复制 MCP 配置到支持它的 Codex 等客户端，让 AI 先调用 list_tasks，再调用 propose_schedule。\n\n软件弹出可逐项选择的预览，由你确认后才修改任务。固定日程不会移动；冲突、超过截止日期或过期建议会被拒绝。", "This version uses external AI through MCP, not a built-in model.\n\nEnable MCP and Allow AI schedule proposals in Labs; full writes are not required. Copy the MCP configuration to a compatible client, then use list_tasks and propose_schedule.\n\nSelect proposals in the local preview and confirm before tasks change. Fixed events, conflicts, deadlines and stale proposals are protected.", "外部AIをMCPで接続します。内蔵モデルはありません。\n\n実験機能でMCPと「AI予定提案を許可」を有効にします。完全書き込みは不要です。設定を対応クライアントにコピーし、list_tasksとpropose_scheduleを使います。\n\nプレビューで項目を選び確認してから保存します。固定予定、競合、期限、古い提案を保護します。", "외부 AI를 MCP로 연결하며 내장 모델은 없습니다.\n\n실험실에서 MCP와 AI 일정 제안 허용을 켜세요. 전체 쓰기는 필요하지 않습니다. 설정을 클라이언트에 복사하고 list_tasks와 propose_schedule을 사용하세요.\n\n미리 보기에서 항목을 선택하고 확인한 뒤 저장합니다. 고정 일정, 충돌, 마감 및 오래된 제안을 보호합니다."],
            ["LabsMcpScheduleProposals"] = ["允许 AI 日程建议", "Allow AI schedule proposals", "AI予定提案を許可", "AI 일정 제안 허용"],
            ["TipLabsMcpScheduleProposals"] = ["仅允许提交候选日程，由你在本机确认保存；不授予直接修改或删除任务的权限。", "Only submit proposed schedules for local confirmation; does not grant direct edits or deletion.", "確認用の予定提案だけを許可します。直接の編集や削除は許可しません。", "현지 확인용 일정 제안만 허용합니다. 직접 수정하거나 삭제할 권한은 부여하지 않습니다."],
            ["PlannerProposalPermissionError"] = ["请在实验功能中开启“允许 AI 日程建议”；无需开启完整写入。", "Enable Allow AI schedule proposals in Labs; full writes are not required.", "実験機能でAI予定提案を許可してください。完全書き込みは不要です。", "실험실에서 AI 일정 제안을 허용하세요. 전체 쓰기는 필요하지 않습니다."],
            ["PlannerDeadlineError"] = ["日程结束不能晚于截止日期，请调整日程或截止日期。", "The schedule must end by the deadline date; adjust the schedule or deadline.", "予定終了は期限日を超えられません。予定か期限を変更してください。", "일정은 마감 날짜까지 끝나야 합니다. 일정이나 마감을 변경하세요."],
            ["PlannerSelectedCount"] = ["已选择 {0}/{1} 项；确认前不会修改任务。", "Selected {0}/{1}; tasks stay unchanged until confirmation.", "{0}/{1}件を選択。確認までは変更しません。", "{0}/{1}개 선택됨. 확인 전에는 변경하지 않습니다."],
            ["PlannerSelectAll"] = ["全选", "Select all", "すべて選択", "모두 선택"],
            ["PlannerSelectNone"] = ["取消全选", "Select none", "選択を解除", "선택 해제"],
            ["PlannerDensityAuto"] = ["间距：自动", "Spacing: automatic", "間隔：自動", "간격: 자동"],
            ["PlannerDensityComfortable"] = ["间距：宽松", "Spacing: comfortable", "間隔：ゆったり", "간격: 여유롭게"],
            ["PlannerDensityCompact"] = ["间距：紧凑", "Spacing: compact", "間隔：コンパクト", "간격: 촘촘하게"],
            ["PlannerLocked"] = ["固定日程（AI 不移动）", "Fixed schedule (AI cannot move)", "固定予定（AIは移動しません）", "고정 일정 (AI 이동 불가)"],
            ["PlannerSave"] = ["保存修改", "Save changes", "変更を保存", "변경 저장"],
            ["PlannerSaved"] = ["已保存。", "Saved.", "保存しました。", "저장됨."],
            ["PlannerShowPaper"] = ["打开原便签", "Open source paper", "元のメモを開く", "원본 메모 열기"],
            ["PlannerReminder"] = ["设置提醒", "Set reminder", "リマインダーを設定", "알림 설정"],
            ["PlannerComplete"] = ["切换完成状态", "Toggle completion", "完了状態を切り替え", "완료 상태 전환"],
            ["PlannerDiscard"] = ["详情有未保存的修改，是否放弃？", "Discard unsaved detail changes?", "未保存の変更を破棄しますか？", "저장하지 않은 변경을 버릴까요?"],
            ["PlannerStale"] = ["任务已被修改，请重新打开详情或重新生成建议。", "Task changed; reopen details or regenerate the proposal.", "タスクが変更されました。詳細を開き直すか提案を再生成してください。", "작업이 변경되었습니다. 상세를 다시 열거나 제안을 다시 생성하세요."],
            ["PlannerConflict"] = ["这个时间段与其他未完成任务冲突，请调整开始或结束时间。", "This interval overlaps another open task; adjust the start or end.", "この時間帯は別の未完了タスクと重なっています。開始または終了を変更してください。", "다른 미완료 작업과 시간이 겹칩니다. 시작 또는 종료를 조정하세요."],
            ["PlannerPreview"] = ["日程建议预览", "Schedule proposal", "予定の提案", "일정 제안"],
            ["PlannerPreviewNotice"] = ["以下是外部 AI 提交的草稿，尚未修改任务。确认时会重新检查冲突和任务版本。", "External AI draft; no tasks changed yet. Conflicts and task versions are rechecked on confirmation.", "外部AIの下書きです。確認時に競合とタスクの版を再確認します。", "외부 AI 초안이며 아직 변경되지 않았습니다. 확인 시 충돌과 버전을 다시 검사합니다."],
            ["PlannerUnscheduled"] = ["未安排", "Unscheduled", "未予定", "미배정"],
            ["PlannerApplySchedule"] = ["确认应用日程", "Confirm schedule", "予定を確認して適用", "일정 확인 및 적용"],
            ["PlannerUndoSchedule"] = ["撤销上次排程", "Undo last schedule", "直前の予定変更を取り消す", "최근 일정 변경 취소"],
            ["PlannerNoUndo"] = ["本次运行中没有可撤销的排程。", "No schedule to undo in this session.", "この起動中に取り消せる予定はありません。", "이번 실행에서 취소할 일정이 없습니다."],
            ["PlannerCancel"] = ["取消", "Cancel", "キャンセル", "취소"],
            ["CodexMeterProviderName"] = ["Codex 状态纸片", "Codex status paper", "Codex ステータス紙", "Codex 상태 메모"],
            ["CodexMeterProviderDescription"] = ["在 PaperNook 中原生查看 Codex 额度、Token、活动、成本和项目统计。", "View Codex quotas, tokens, activity, cost and project usage natively in PaperNook.", "PaperNook で Codex の使用枠、トークン、アクティビティ、コスト、プロジェクト統計を表示します。", "PaperNook에서 Codex 할당량, 토큰, 활동, 비용 및 프로젝트 통계를 기본 UI로 확인합니다."],
            ["CodexMeterPaperTitle"] = ["Codex 状态", "Codex status", "Codex ステータス", "Codex 상태"],
            ["CodexMeterOpen"] = ["打开 Codex 状态纸片", "Open Codex status paper", "Codex ステータス紙を開く", "Codex 상태 메모 열기"],
            ["CodexMeterHeading"] = ["Codex 用量", "Codex usage", "Codex 使用状況", "Codex 사용량"],
            ["CodexMeterRefresh"] = ["刷新 Codex 数据", "Refresh Codex data", "Codex データを更新", "Codex 데이터 새로 고침"],
            ["CodexMeterRefreshInterval"] = ["刷新间隔", "Refresh interval", "更新間隔", "새로 고침 간격"],
            ["CodexMeterRefreshIntervalDescription"] = ["只在存在 Codex 状态纸片时按此间隔读取本机数据。", "Read local data at this interval only while a Codex status paper exists.", "Codex ステータス紙がある間だけ、この間隔でローカルデータを読み取ります。", "Codex 상태 메모가 있을 때만 이 간격으로 로컬 데이터를 읽습니다."],
            ["CodexMeterSeconds"] = ["秒", "sec", "秒", "초"],
            ["CodexMeterShowCost"] = ["显示 API 等价成本", "Show API-equivalent cost", "API 換算コストを表示", "API 환산 비용 표시"],
            ["CodexMeterShowCostDescription"] = ["按公开模型单价估算本机日志，不代表订阅账单。", "Estimate local logs with public model prices; this is not a subscription bill.", "公開モデル価格でローカルログを推定します。サブスクリプション請求額ではありません。", "공개 모델 가격으로 로컬 로그를 추정하며 구독 청구액이 아닙니다."],
            ["CodexMeterCreateOnStartup"] = ["启动时创建纸片", "Create paper at startup", "起動時に紙を作成", "시작할 때 메모 만들기"],
            ["CodexMeterCreateOnStartupDescription"] = ["没有现有 Codex 状态纸片时，在下次启动自动创建一张。", "Create one on the next launch when no Codex status paper exists.", "既存の Codex ステータス紙がない場合、次回起動時に作成します。", "기존 Codex 상태 메모가 없으면 다음 시작 시 하나 만듭니다."],
            ["CodexMeterAccountScope"] = ["统计账号范围", "Account scope", "アカウント範囲", "계정 범위"],
            ["CodexMeterAccountScopeDescription"] = ["当前账号更适合查看额度；全部账号用于汇总本机历史用量。", "Use the current account for quotas, or all accounts for combined local history.", "現在のアカウントは使用枠、全アカウントはローカル履歴の集計に使用します。", "현재 계정은 할당량, 모든 계정은 로컬 기록 합계에 사용합니다."],
            ["CodexMeterCurrentAccount"] = ["当前账号", "Current account", "現在のアカウント", "현재 계정"],
            ["CodexMeterAllAccounts"] = ["本机全部账号", "All local accounts", "ローカルの全アカウント", "모든 로컬 계정"],
            ["CodexMeterLocalAccount"] = ["本机 Codex", "Local Codex", "ローカル Codex", "로컬 Codex"],
            ["CodexMeterAccountFormat"] = ["账号 {0}", "Account {0}", "アカウント {0}", "계정 {0}"],
            ["CodexMeterUnknownProject"] = ["未知目录", "Unknown folder", "不明なフォルダー", "알 수 없는 폴더"],
            ["CodexMeterCodexNotFound"] = ["PATH 中找不到 Codex CLI；Token 统计仍可使用。", "Codex CLI was not found on PATH; token statistics remain available.", "PATH に Codex CLI が見つかりません。トークン統計は引き続き利用できます。", "PATH에서 Codex CLI를 찾지 못했습니다. 토큰 통계는 계속 사용할 수 있습니다."],
            ["CodexMeterRpcInitializeFailedFormat"] = ["初始化 Codex 额度服务失败：{0}", "Could not initialize the Codex quota service: {0}", "Codex 使用枠サービスを初期化できませんでした：{0}", "Codex 할당량 서비스를 초기화하지 못했습니다: {0}"],
            ["CodexMeterRpcReadFailedFormat"] = ["读取 Codex 额度失败：{0}", "Could not read Codex quotas: {0}", "Codex 使用枠を読み取れませんでした：{0}", "Codex 할당량을 읽지 못했습니다: {0}"],
            ["CodexMeterRpcTimeout"] = ["读取 Codex 额度超时。", "Reading Codex quotas timed out.", "Codex 使用枠の読み取りがタイムアウトしました。", "Codex 할당량 읽기 시간이 초과되었습니다."],
            ["CodexMeterRpcFailedFormat"] = ["Codex 额度服务不可用：{0}", "Codex quota service is unavailable: {0}", "Codex 使用枠サービスを利用できません：{0}", "Codex 할당량 서비스를 사용할 수 없습니다: {0}"],
            ["CodexMeterUnavailable"] = ["暂不可用", "Unavailable", "利用不可", "사용할 수 없음"],
            ["CodexMeterActivityThinking"] = ["思考中", "Thinking", "思考中", "생각 중"],
            ["CodexMeterActivityTool"] = ["执行工具", "Using tools", "ツール実行中", "도구 실행 중"],
            ["CodexMeterActivityAnswering"] = ["生成回答", "Answering", "回答生成中", "답변 생성 중"],
            ["CodexMeterActivityActive"] = ["活动中", "Active", "アクティブ", "활성"],
            ["CodexMeterActivityIdle"] = ["空闲", "Idle", "待機中", "유휴"],
            ["CodexMeterActivityWaiting"] = ["等待确认", "Awaiting input", "入力待ち", "입력 대기"],
            ["CodexMeterActivityUnknown"] = ["状态待确认", "Activity unverified", "状態未確認", "상태 확인 필요"],
            ["CodexMeterActivityCountFormat"] = ["{0} · {1} 个任务", "{0} · {1} tasks", "{0}・{1} 件", "{0} · 작업 {1}개"],
            ["CodexMeterCapsuleTooltipFormat"] = ["Codex {0}；{1}", "Codex {0}; {1}", "Codex {0}、{1}", "Codex {0}; {1}"],
            ["CodexMeterFiveHour"] = ["5 小时", "5 hours", "5 時間", "5시간"],
            ["CodexMeterSevenDay"] = ["7 天", "7 days", "7 日", "7일"],
            ["CodexMeterTokens"] = ["Token", "Tokens", "トークン", "토큰"],
            ["CodexMeterCost"] = ["本周期成本", "Cycle cost", "周期コスト", "주기 비용"],
            ["CodexMeterSessions"] = ["会话", "Sessions", "セッション", "세션"],
            ["CodexMeterTopProjects"] = ["用量最高的项目", "Top projects", "使用量上位プロジェクト", "사용량 상위 프로젝트"],
            ["CodexMeterNoSessions"] = ["还没有可统计的 Codex 会话。", "No Codex sessions are available yet.", "集計できる Codex セッションはまだありません。", "집계할 Codex 세션이 아직 없습니다."],
            ["CodexMeterQuotaUnavailable"] = ["额度暂不可用", "Quota unavailable", "使用枠を取得できません", "할당량을 사용할 수 없음"],
            ["CodexMeterSourceFormat"] = ["来源：{0}", "Source: {0}", "ソース：{0}", "출처: {0}"],
            ["CodexMeterResetsFormat"] = ["{0} 重置", "Resets {0}", "{0} にリセット", "{0} 재설정"],
            ["CodexMeterResetUnknown"] = ["重置时间未知", "Reset time unknown", "リセット時刻不明", "재설정 시간 알 수 없음"],
            ["CodexMeterWaitingForData"] = ["等待本机 Codex 数据", "Waiting for local Codex data", "ローカル Codex データを待機中", "로컬 Codex 데이터 대기 중"],
            ["CodexMeterLoading"] = ["读取中", "Loading", "読み込み中", "불러오는 중"],
            ["CodexMeterLoadingDetail"] = ["首次扫描在后台进行，不会阻塞纸片。", "The first scan runs in the background without blocking the paper.", "初回スキャンは紙をブロックせずバックグラウンドで実行されます。", "첫 스캔은 메모를 차단하지 않고 백그라운드에서 실행됩니다."],
            ["CodexMeterRefreshing"] = ["正在刷新本机数据…", "Refreshing local data…", "ローカルデータを更新中…", "로컬 데이터 새로 고침 중…"],
            ["CodexMeterExport"] = ["导出 Codex 用量", "Export Codex usage", "Codex 使用量をエクスポート", "Codex 사용량 내보내기"],
            ["CodexMeterExportJson"] = ["JSON 数据", "JSON data", "JSON データ", "JSON 데이터"],
            ["CodexMeterExportCsv"] = ["CSV 每日统计", "CSV daily usage", "CSV 日別統計", "CSV 일별 통계"],
            ["CodexMeterExportFailedFormat"] = ["导出失败：{0}", "Export failed: {0}", "エクスポートに失敗しました：{0}", "내보내기 실패: {0}"],
            ["CodexMeterAnalysis"] = ["用量分析", "Usage analysis", "使用量分析", "사용량 분석"],
            ["CodexMeterToday"] = ["今天", "Today", "今日", "오늘"],
            ["CodexMeterThirtyDays"] = ["30 天", "30 days", "30 日", "30일"],
            ["CodexMeterNinetyDays"] = ["90 天", "90 days", "90 日", "90일"],
            ["CodexMeterDailyTrend"] = ["最近 7 天", "Last 7 days", "最近 7 日", "최근 7일"],
            ["CodexMeterComponents"] = ["本机组件", "Local components", "ローカルコンポーネント", "로컬 구성 요소"],
            ["CodexMeterComponentCountsFormat"] = ["Skill {0} · Plugin {1} · MCP {2}", "Skills {0} · Plugins {1} · MCP {2}", "Skill {0}・Plugin {1}・MCP {2}", "Skill {0} · Plugin {1} · MCP {2}"],
            ["CodexMeterNetwork"] = ["网络诊断", "Network diagnostics", "ネットワーク診断", "네트워크 진단"],
            ["CodexMeterCheckNetwork"] = ["检查官方服务", "Check official services", "公式サービスを確認", "공식 서비스 확인"],
            ["CodexMeterNetworkNotChecked"] = ["仅在手动检查时连接 ChatGPT 与 OpenAI API。", "Connects to ChatGPT and the OpenAI API only when checked manually.", "手動確認時のみ ChatGPT と OpenAI API に接続します。", "수동 확인 시에만 ChatGPT와 OpenAI API에 연결합니다."],
            ["CodexMeterNetworkReachableFormat"] = ["{0} 可达 · {1} ms", "{0} reachable · {1} ms", "{0} 到達可能・{1} ms", "{0} 연결 가능 · {1} ms"],
            ["CodexMeterNetworkFailedFormat"] = ["{0} 不可达", "{0} unreachable", "{0} 到達不可", "{0} 연결 불가"],
            ["CodexMeterQuotaLive"] = ["官方实时额度", "Live official quota", "公式リアルタイム使用枠", "공식 실시간 할당량"],
            ["CodexMeterQuotaCache"] = ["官方缓存额度", "Cached official quota", "公式キャッシュ使用枠", "공식 캐시 할당량"],
            ["CodexMeterQuotaSession"] = ["会话回退额度", "Session fallback quota", "セッション代替使用枠", "세션 대체 할당량"],
            ["CodexMeterQuotaMixed"] = ["混合来源额度（最旧）", "Mixed quota sources (oldest)", "混合使用枠（最古）", "혼합 할당량 출처(가장 오래됨)"],
            ["CodexMeterQuotaAgeFormat"] = ["{0} · {1} 分钟前", "{0} · {1} min ago", "{0}・{1} 分前", "{0} · {1}분 전"],
            ["CodexMeterQuotaDiagnosticsFormat"] = ["初始化 {0} ms · 额度 {1} ms", "Init {0} ms · quota {1} ms", "初期化 {0} ms・使用枠 {1} ms", "초기화 {0} ms · 할당량 {1} ms"],
            ["CodexMeterTabOverview"] = ["概览", "Overview", "概要", "개요"],
            ["CodexMeterTabAnalysis"] = ["分析", "Analysis", "分析", "분석"],
            ["CodexMeterTabProjects"] = ["项目", "Projects", "プロジェクト", "프로젝트"],
            ["CodexMeterTabDiagnostics"] = ["诊断", "Diagnostics", "診断", "진단"],
            ["CodexMeterTokenBreakdown"] = ["Token 构成", "Token breakdown", "トークン内訳", "토큰 구성"],
            ["CodexMeterTokenBreakdownFormat"] = ["输入 {0} · 缓存 {1} · 输出 {2} · 推理 {3}", "Input {0} · cached {1} · output {2} · reasoning {3}", "入力 {0}・キャッシュ {1}・出力 {2}・推論 {3}", "입력 {0} · 캐시 {1} · 출력 {2} · 추론 {3}"],
            ["CodexMeterCycleHistory"] = ["额度周期历史", "Quota cycle history", "使用枠サイクル履歴", "할당량 주기 기록"],
            ["CodexMeterCycleRowFormat"] = ["{0} 重置 · 剩余 {1}% · {2}", "Reset {0} · {1}% left · {2}", "{0} リセット・残り {1}%・{2}", "{0} 재설정 · {1}% 남음 · {2}"],
            ["CodexMeterRecentSessions"] = ["最近会话", "Recent sessions", "最近のセッション", "최근 세션"],
            ["CodexMeterResumeSession"] = ["继续", "Resume", "再開", "계속"],
            ["CodexMeterRecycleSession"] = ["回收", "Recycle", "回収", "휴지통"],
            ["CodexMeterRecycledSessions"] = ["可恢复的会话", "Recoverable sessions", "復元可能なセッション", "복구 가능한 세션"],
            ["CodexMeterRestoreSession"] = ["恢复", "Restore", "復元", "복원"],
            ["CodexMeterRecycleConfirmFormat"] = ["将会话 {0} 移入 PaperNook 回收区？原始 JSONL 会保留为可恢复副本。", "Move session {0} to the PaperNook recycle area? Its JSONL remains recoverable.", "セッション {0} を PaperNook の回収領域に移動しますか？JSONL は復元できます。", "세션 {0}을 PaperNook 휴지통으로 이동할까요? JSONL은 복구할 수 있습니다."],
            ["CodexMeterSessionActionFailedFormat"] = ["会话操作失败：{0}", "Session action failed: {0}", "セッション操作に失敗しました：{0}", "세션 작업 실패: {0}"],
            ["CodexMeterSessionRecycled"] = ["会话已移入可恢复回收区。", "Session moved to the recoverable recycle area.", "セッションを復元可能な回収領域へ移動しました。", "세션을 복구 가능한 휴지통으로 이동했습니다."],
            ["CodexMeterSessionRestored"] = ["会话已恢复。", "Session restored.", "セッションを復元しました。", "세션을 복원했습니다."],
            ["CodexMeterSessionRestoreConflict"] = ["原位置已有文件，未覆盖；请先处理冲突。", "A file already exists at the original location; nothing was overwritten.", "元の場所にファイルがあるため上書きしませんでした。", "원래 위치에 파일이 있어 덮어쓰지 않았습니다."],
            ["CodexMeterCopyDiagnostics"] = ["复制脱敏诊断", "Copy sanitized diagnostics", "匿名化診断をコピー", "민감 정보 제거 진단 복사"],
            ["CodexMeterDiagnosticsCopied"] = ["脱敏诊断已复制。", "Sanitized diagnostics copied.", "匿名化診断をコピーしました。", "민감 정보 제거 진단을 복사했습니다."],
            ["CodexMeterDiagnosticsCopyFailedFormat"] = ["复制诊断失败：{0}", "Could not copy diagnostics: {0}", "診断をコピーできませんでした：{0}", "진단을 복사하지 못했습니다: {0}"],
            ["CodexMeterPriceCatalogFormat"] = ["API 等价成本估算；价格表日期 {0}，不代表订阅账单。", "API-equivalent estimate; price catalog dated {0}, not a subscription bill.", "API 換算見積もり；価格表は {0} 時点、請求額ではありません。", "API 환산 예상치이며 가격표 기준일은 {0}이고 구독 청구액이 아닙니다."],
            ["CodexMeterCurrency"] = ["成本显示货币", "Cost display currency", "コスト表示通貨", "비용 표시 통화"],
            ["CodexMeterCurrencyDescription"] = ["人民币按欧洲央行参考汇率换算，仅在选择时联网并缓存 24 小时。", "CNY uses the ECB reference rate and only connects when selected, with a 24-hour cache.", "CNY は ECB 参照レートを使用し、選択時のみ接続して 24 時間キャッシュします。", "CNY는 ECB 기준 환율을 사용하며 선택한 경우에만 연결하고 24시간 캐시합니다."],
            ["CodexMeterCurrencyUsd"] = ["美元（USD）", "US dollar (USD)", "米ドル（USD）", "미국 달러(USD)"],
            ["CodexMeterCurrencyCny"] = ["人民币（CNY）", "Chinese yuan (CNY)", "中国元（CNY）", "중국 위안(CNY)"],
            ["CodexMeterExchangeRateFormat"] = ["汇率：ECB {0} · {1}", "Exchange: ECB {0} · {1}", "為替：ECB {0}・{1}", "환율: ECB {0} · {1}"],
            ["SettingsUiLanguage"] = ["界面语言", "Interface language", "表示言語", "인터페이스 언어"],
            ["TipSettingsUiLanguage"] = ["选择界面语言；重启 PaperNook 后生效。", "Choose the interface language; restart PaperNook to apply.", "表示言語を選択します。PaperNook の再起動後に反映されます。", "인터페이스 언어를 선택합니다. PaperNook를 다시 시작하면 적용됩니다."],
            ["UiLanguageSystem"] = ["跟随系统", "Follow system", "システムに従う", "시스템 설정 따름"],
            ["UiLanguageZhHans"] = ["简体中文", "简体中文", "简体中文", "简体中文"],
            ["UiLanguageEnglish"] = ["English", "English", "English", "English"],
            ["UiLanguageJapanese"] = ["日本語", "日本語", "日本語", "日本語"],
            ["UiLanguageKorean"] = ["한국어", "한국어", "한국어", "한국어"],
            ["SettingsDistinguishNumpadShortcutDigits"] = ["区分小键盘数字键", "Distinguish numpad digits", "テンキー数字を区別", "숫자 키패드 숫자 구분"],
            ["TipSettingsDistinguishNumpadShortcutDigits"] = ["开启后数字键与小键盘数字键可分别注册；关闭后两者混合响应，但不会修改已保存的快捷键。快速启动侧边胶囊不受影响。", "When enabled, number-row and numpad digits can be registered separately. When disabled, either key triggers the stored binding without rewriting it. Edge quick-launch sequences are unchanged.", "オンでは数字列とテンキーを別々に登録できます。オフでは保存値を書き換えず両方で反応します。端のクイック起動シーケンスには影響しません。", "켜면 숫자열과 숫자 키패드를 따로 등록할 수 있습니다. 끄면 저장된 값을 바꾸지 않고 둘 다 반응합니다. 가장자리 빠른 실행 시퀀스에는 영향을 주지 않습니다."],
            ["ShortcutNumpadModeConflictTitle"] = ["小键盘快捷键冲突", "Numpad shortcut conflict", "テンキーショートカットの競合", "숫자 키패드 단축키 충돌"],
            ["ShortcutNumpadModeConflictMessage"] = ["无法切换小键盘模式：现有快捷键存在数字键/小键盘冲突，或混合响应所需的组合已被其他程序占用。现有快捷键不会被修改。", "The numpad mode could not be changed because existing bindings conflict across number-row/numpad digits, or a required mixed-mode combination is already owned by another app. Existing bindings were not changed.", "既存の数字列/テンキー割り当てが競合しているか、混合応答に必要な組み合わせを他のアプリが使用しているため切り替えできません。既存の割り当ては変更されません。", "기존 숫자열/숫자 키패드 바인딩이 충돌하거나 혼합 응답에 필요한 조합을 다른 앱이 사용 중이라 모드를 변경할 수 없습니다. 기존 바인딩은 변경되지 않습니다."],
            ["LabsAdvancedShortcuts"] = ["高级快捷键", "Advanced shortcuts", "高度なショートカット", "고급 바로 가기"],
            ["LabsFocusInactiveGroup"] = ["失焦", "Inactive", "非アクティブ", "비활성"],
            ["LabsFocusRestingGroup"] = ["静置", "Resting", "静置", "유휴"],
            ["LabsDockedCapsuleBehavior"] = ["贴边胶囊", "Docked capsules", "端のカプセル", "가장자리 캡슐"],
            ["LabsFocusRestingOpacity"] = ["静置时自动半透明", "Fade while resting", "静置時に自動で半透明", "유휴 시 자동 반투명"],
            ["TipLabsFocusRestingOpacity"] = ["仅影响普通胶囊和贴边胶囊的静置状态；悬停、激活或拖动时恢复为不透明。默认不影响主胶囊，可在下方选择同时应用。", "Affects ordinary and docked capsules while resting; hover, activation, or dragging restores full opacity. The master capsule is excluded by default and can be included below.", "通常カプセルと端のカプセルの静置時だけ半透明にし、ホバー・アクティブ化・ドラッグで不透明に戻します。マスターカプセルは既定では対象外で、下の項目から含められます。", "일반 캡슐과 가장자리 캡슐의 유휴 상태에만 적용되며, 호버·활성화·드래그 시 불투명하게 돌아옵니다. 마스터 캡슐은 기본적으로 제외되며 아래에서 포함할 수 있습니다."],
            ["LabsFocusRestingIncludeMaster"] = ["主胶囊也透明", "Include master capsule", "マスターカプセルにも適用", "마스터 캡슐도 투명"],
            ["LabsFocusRestingAlways"] = ["激活时也保持透明", "Keep transparent while active", "操作中も透明を維持", "활성 상태에서도 투명 유지"],
            ["TipLabsWindowTetheringFixed"] = ["展开纸片后，把顶栏的窗口绑定按钮拖到其他软件窗口并松手，纸片会贴边并跟随移动；折叠与重新展开会保持同一绑定。目标窗口最小化或隐藏时纸片会暂时隐藏并等待恢复；等待期间手动显示纸片会解除绑定。", "After expanding a paper, drag its top-bar window-binding button onto another app window and release to attach and follow it. Folding and expanding keep the same binding. If the target is minimized or hidden, the paper waits hidden and returns with the target; explicitly showing it while waiting detaches the binding.", "紙を展開した後、上部バーのウィンドウ連携ボタンを別アプリのウィンドウへドラッグして離すと、そのウィンドウに沿って追従します。折りたたみと再展開でも同じ連携を維持します。対象が最小化または非表示になると紙も一時的に隠れて復帰を待ち、待機中に手動で表示すると連携を解除します。", "메모를 펼친 뒤 상단 바의 창 연결 버튼을 다른 앱 창으로 드래그해 놓으면 해당 창 가장자리에 붙어 따라갑니다. 접고 다시 펼쳐도 같은 연결을 유지합니다. 대상 창이 최소화되거나 숨겨지면 메모도 임시로 숨은 채 복원을 기다리며, 대기 중 수동으로 표시하면 연결을 해제합니다."],
            ["LabsInteractionLock"] = ["交互锁定", "Interaction lock", "操作ロック", "상호 작용 잠금"],
            ["LabsLockAllPapers"] = ["锁定全部便签", "Lock all papers", "すべての紙をロック", "모든 메모 잠금"],
            ["TipLabsLockAllPapers"] = ["切换全部普通与插件便签的交互锁定。", "Toggle interaction lock for all regular and plugin papers.", "通常およびプラグインの紙をすべてロックします。", "일반 및 플러그인 메모를 모두 잠급니다."],
            ["LabsAllowLockIconUnlock"] = ["允许点击锁头解锁", "Allow lock icon to unlock", "ロックアイコンで解除を許可", "잠금 아이콘으로 해제 허용"],
            ["TipLabsAllowLockIconUnlock"] = ["关闭后锁头仅作提示，只能通过快捷键解锁。", "When off, the lock is only an indicator and the shortcut is required to unlock.", "オフの場合、ロックは表示のみで解除にはショートカットが必要です。", "끄면 잠금은 표시만 하며 단축키로만 해제할 수 있습니다."],
            ["LabsUnlockAllPapers"] = ["解锁全部便签", "Unlock all papers", "すべての紙のロックを解除", "모든 메모 잠금 해제"],
            ["LabsShortcutTransparency"] = ["快捷透明度", "Shortcut transparency", "ショートカット透明度", "단축키 투명도"],
            ["LabsShortcutOpacityLevel"] = ["透明度值", "Opacity level", "透明度", "투명도 값"],
            ["LabsAllPapersTransparent"] = ["切换全部纸片透明", "Toggle all papers transparent", "すべての紙の透明を切替", "모든 메모 투명 전환"],
            ["TipLabsAllPapersTransparent"] = ["部分透明时会先统一设为透明；全部已透明时再次按下才取消。", "If only some are transparent, all become transparent; press again only when all are transparent to cancel.", "一部だけ透明な場合はすべて透明にし、全て透明な場合のみ再度押すと解除します。", "일부만 투명하면 모두 투명하게 만들고, 모두 투명할 때 다시 눌러 해제합니다."],
            ["LabsAllCapsulesTransparent"] = ["切换全部胶囊透明", "Toggle all capsules transparent", "すべてのカプセルの透明を切替", "모든 캡슐 투명 전환"],
            ["TipLabsAllCapsulesTransparent"] = ["显式透明优先于空闲半透明，并统一作用于全部胶囊。", "Explicit transparency overrides idle transparency and applies to all capsules.", "明示的な透明度はアイドル透明度より優先され、全カプセルに適用されます。", "명시적 투명도는 유휴 투명도보다 우선하며 모든 캡슐에 적용됩니다."],
            ["LabsCurrentPaperTransparent"] = ["切换当前焦点纸片透明", "Toggle focused paper transparent", "フォーカス中の紙の透明を切替", "현재 포커스 메모 투명 전환"],
            ["TipLabsCurrentPaperTransparent"] = ["只作用于快捷键触发时拥有焦点的普通或插件纸片。", "Affects only the regular or plugin paper focused when the shortcut fires.", "ショートカット実行時にフォーカス中の通常またはプラグインの紙だけに作用します。", "단축키 실행 시 포커스된 일반 또는 플러그인 메모에만 적용됩니다."],
            ["LabsHideInactiveTopBarButtons"] = ["失焦隐藏顶栏按钮", "Hide inactive top-bar buttons", "非アクティブ時に上部ボタンを隠す", "비활성 상단 버튼 숨기기"],
            ["TipLabsHideInactiveTopBarButtons"] = ["纸片失去焦点时隐藏顶栏操作按钮；悬停或重新激活时显示，并保留原布局空间。", "Hide top-bar action buttons while the paper is inactive; reveal them on hover or activation without changing layout.", "紙が非アクティブな間は上部の操作ボタンを隠し、ホバーまたは再アクティブ化で表示します。レイアウト幅は保持します。", "메모가 비활성일 때 상단 작업 버튼을 숨기고, 마우스를 올리거나 다시 활성화하면 표시합니다. 레이아웃 공간은 유지합니다."],
            ["LabsHideInactiveTitleBar"] = ["失焦隐藏标题栏", "Hide inactive title bar", "非アクティブ時にタイトルバーを隠す", "비활성 제목 표시줄 숨기기"],
            ["TipLabsHideInactiveTitleBar"] = ["浮动纸片失焦时淡出标题栏区域，完全隐藏后可点击到后面的窗口；窗口尺寸、正文与底边位置不动，重新激活时恢复。最大化和 Snap 状态保持完整标题栏。", "Fade out the title-bar area when a floating paper becomes inactive. Once fully hidden, clicks pass through to windows behind it. Window size, body and bottom edge stay fixed; activation restores the title bar. Maximized and snapped papers keep the full title bar.", "フローティング紙が非アクティブになるとタイトルバー領域をフェードアウトし、完全に隠れた領域は背後のウィンドウをクリックできます。ウィンドウサイズ、本文と下端の位置は変わらず、再アクティブ化で復元します。最大化・スナップ時はタイトルバーを表示します。", "플로팅 메모가 비활성화되면 제목 표시줄 영역이 서서히 사라지며, 완전히 숨겨진 영역에서는 뒤쪽 창을 클릭할 수 있습니다. 창 크기와 본문 및 아래쪽 위치는 유지되며 다시 활성화하면 복원됩니다. 최대화 및 스냅 상태에서는 전체 제목 표시줄을 유지합니다."],
            ["LabsDockedCapsulesNonTopmost"] = ["允许贴边胶囊非置顶", "Allow docked capsules below topmost", "端に固定したカプセルの非最前面を許可", "가장자리 캡슐 비고정 허용"],
            ["TipLabsDockedCapsulesNonTopmost"] = ["开启后贴边胶囊和主胶囊不再保持置顶；展开纸片仍按自身置顶设置。", "When enabled, docked and master capsules no longer stay topmost; expanded papers keep their own topmost setting.", "有効にすると端のカプセルとマスターカプセルは最前面を維持せず、展開した紙は個別設定に従います。", "켜면 가장자리 및 마스터 캡슐이 항상 위를 유지하지 않으며 펼친 메모는 자체 설정을 따릅니다."],
            ["LabsFocusOpacity"] = ["失焦与静止透明", "Inactive and resting transparency", "非アクティブ・静止時の透明度", "비활성·정지 투명도"],
            ["LabsRestingCapsuleOpacityIncludeMaster"] = ["覆盖主胶囊", "Include master capsule", "マスターカプセルにも適用", "마스터 캡슐에도 적용"],
            ["LabsRestingCapsuleOpacityAlways"] = ["无论是否激活都透明", "Keep transparent while active", "操作中も透明を維持", "활성 상태에서도 투명 유지"],
            ["LabsMcpCopyAiSkill"] = ["复制 AI Skill", "Copy AI skill", "AI Skill をコピー", "AI Skill 복사"],
            ["SettingsAutoMoveCompletedTodosToBottom"] = ["已完成待办自动置底", "Move completed todos to bottom", "完了したToDoを下へ移動", "완료된 할 일을 아래로 이동"],
            ["TipAutoMoveCompletedTodosToBottom"] = ["完成待办时移到已完成区域末尾；取消完成时移到未完成区域末尾。开启“自动清除已完成待办”时暂时禁用，但会保留此设置。", "Move a completed todo to the end of the completed group; restoring it moves it to the end of the active group. This is temporarily disabled while auto-clear is on, without forgetting the setting.", "完了時は完了グループの末尾へ、未完了に戻すと未完了グループの末尾へ移動します。完了項目の自動削除中は無効になりますが、設定値は保持されます。", "완료하면 완료 그룹의 끝으로, 완료를 취소하면 미완료 그룹의 끝으로 이동합니다. 완료 항목 자동 삭제가 켜져 있으면 잠시 비활성화되지만 설정은 유지됩니다."],
            ["LabsTodoReminderSoundEnabled"] = ["允许提醒声音", "Play reminder sound", "リマインダー音を鳴らす", "미리 알림 소리 허용"],
            ["TipLabsTodoReminderSoundEnabled"] = ["开启后提醒触发时播放声音。程序目录中的有效 papertodo.wav 会优先于所选 Windows 系统声音。", "Play a sound when a reminder fires. A valid papertodo.wav beside the app takes priority over the selected Windows system sound.", "有効にするとリマインダー時に音を鳴らします。アプリと同じフォルダーの有効な papertodo.wav が、選択した Windows システム音より優先されます。", "켜면 미리 알림이 울릴 때 소리를 재생합니다. 프로그램 폴더의 유효한 papertodo.wav가 선택한 Windows 시스템 소리보다 우선합니다."],
            ["LabsTodoReminderSound"] = ["提醒声音", "Reminder sound", "リマインダー音", "미리 알림 소리"],
            ["TipLabsTodoReminderSound"] = ["选择 Windows 系统声音。若程序目录存在可读取的 papertodo.wav，则自动优先使用；文件无效或播放失败时回退到这里的选择。", "Choose a Windows system sound. A readable papertodo.wav beside the app is used first; invalid or failed custom audio falls back to this choice.", "Windows のシステム音を選びます。アプリと同じフォルダーに読み取り可能な papertodo.wav があれば優先し、無効または再生失敗時はこの音へ戻ります。", "Windows 시스템 소리를 선택합니다. 프로그램 폴더에 읽을 수 있는 papertodo.wav가 있으면 우선 사용하며, 유효하지 않거나 재생에 실패하면 이 선택으로 돌아갑니다."],
            ["TodoReminderSoundAsterisk"] = ["提示音", "Asterisk", "通知", "알림"],
            ["TodoReminderSoundBeep"] = ["蜂鸣", "Beep", "ビープ", "비프"],
            ["TodoReminderSoundExclamation"] = ["感叹", "Exclamation", "警告", "경고"],
            ["TodoReminderSoundHand"] = ["严重警告", "Critical stop", "重大な警告", "심각한 경고"],
            ["TodoReminderSoundQuestion"] = ["询问", "Question", "質問", "질문"],
            ["TodoPasteTruncatedTitle"] = ["粘贴内容已截断", "Paste was truncated", "貼り付け内容を切り詰めました", "붙여넣기 내용이 잘렸습니다"],
            ["TodoPasteItemLimitMessage"] = ["本次最多插入前 {0} 条待办，其余未插入。", "Only the first {0} todos were inserted; the rest were not inserted.", "先頭の {0} 件だけを挿入し、残りは挿入しませんでした。", "앞의 {0}개 할 일만 삽입했고 나머지는 삽입하지 않았습니다."],
            ["TodoPasteTextLimitMessage"] = ["待办最多支持 {0} 个字符，超出部分未插入。", "A todo can contain at most {0} characters; excess text was not inserted.", "ToDo は最大 {0} 文字です。超えた部分は挿入しませんでした。", "할 일은 최대 {0}자까지 지원하며 초과한 텍스트는 삽입하지 않았습니다."],
            ["NoteInputLimitTitle"] = ["笔记已达上限", "Note limit reached", "ノートの上限に達しました", "메모 한도에 도달했습니다"],
            ["NoteInputLimitMessage"] = ["笔记最多支持 {0} 个字符。请删除部分内容后再继续输入。", "A note can contain at most {0} characters. Delete some content before typing more.", "ノートは最大 {0} 文字です。続けて入力するには一部の内容を削除してください。", "메모는 최대 {0}자까지 입력할 수 있습니다. 계속 입력하려면 일부 내용을 삭제해 주세요."]
        };

    public static string Get(string key)
    {
        var uiCulture = UiLanguages.EffectiveUiCulture;
        var resource = Manager.GetString(key, uiCulture);
        if (resource != null)
        {
            return resource;
        }

        if (!Supplemental.TryGetValue(key, out var values))
        {
            return key;
        }

        return uiCulture.TwoLetterISOLanguageName switch
        {
            "en" => values[1],
            "ja" => values[2],
            "ko" => values[3],
            _ => values[0]
        };
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(UiLanguages.EffectiveCulture, Get(key), args);
    }
}
